"""
All tutorial page content. Plain strings and ASCII art.
Each page is a dict with: title, section, body (list of lines), art (optional list of lines).
"""

# ── ASCII Art ──────────────────────────────────────────────

PAW_LOGO = [
    r"        _______________        ",
    r"       /               \       ",
    r"      |  ┌───┐ ┌───┐  |       ",
    r"      |  │ ● │ │ ● │  |       ",
    r"      |  └───┘ └───┘  |       ",
    r"      |      ___      |       ",
    r"      |     /   \     |       ",
    r"      |    | === |    |       ",
    r"       \   \_____/   /        ",
    r"        \___________/         ",
    r"         /    |    \          ",
    r"        *     *     *         ",
]

SHIELD_ART = [
    r"       ╔═══════════╗    ",
    r"       ║  ┌─────┐  ║    ",
    r"       ║  │ ██  │  ║    ",
    r"       ║  │ ███ │  ║    ",
    r"       ║  │ ██  │  ║    ",
    r"       ║  └─────┘  ║    ",
    r"       ╚═════╦═════╝    ",
    r"             ║          ",
    r"         HOOKS          ",
    r"       ENFORCE          ",
]

FLOW_ART = [
    r"  ┌──────────┐     ┌──────────┐     ┌──────────┐  ",
    r"  │  AGENTS  │────▶│  SKILLS  │     │ CONTEXTS │  ",
    r"  │ 18 roles │     │  domain  │     │  mindset │  ",
    r"  └────┬─────┘     └──────────┘     └──────────┘  ",
    r"       │                                  │        ",
    r"       │ reference                   loaded by     ",
    r"       ▼                                  │        ",
    r"  ┌──────────┐                            │        ",
    r"  │  RULES   │◄───────────────────────────┘        ",
    r"  │ 6 pages  │                                     ",
    r"  └────┬─────┘                                     ",
    r"       │ enforced by                               ",
    r"       ▼                                           ",
    r"  ┌──────────┐                                     ",
    r"  │  HOOKS   │  ◄── fire on Claude Code events     ",
    r"  └──────────┘                                     ",
]

ROCKET_ART = [
    r"           /\          ",
    r"          /  \         ",
    r"         / || \        ",
    r"        /  ||  \       ",
    r"       /   ||   \      ",
    r"      / ┌──────┐ \    ",
    r"     /  │ paw  │  \   ",
    r"    /   │  =>  │   \  ",
    r"   /    │forge │    \ ",
    r"  ╱     └──────┘     ╲",
    r" ╱___________________╲",
    r"     ╱╱╱    ╲╲╲       ",
    r"    ╱╱╱      ╲╲╲      ",
]

AGENTS_ART = [
    r"  ┌────────────────────────────────────────────┐",
    r"  │          18 SPECIALIZED AGENTS              │",
    r"  ├──────────────┬─────────────┬───────────────┤",
    r"  │   PLAN       │  BUILD      │  REVIEW       │",
    r"  ├──────────────┼─────────────┼───────────────┤",
    r"  │ architect    │ builder     │ code-reviewer  │",
    r"  │ planner      │ merge-      │ bug-auditor    │",
    r"  │ devils-      │  resolver   │ security       │",
    r"  │  advocate    │ migration-  │ perf-checker   │",
    r"  │ rollback-    │  architect  │ fe-reviewer    │",
    r"  │  planner     │             │ php-reviewer   │",
    r"  │              │  RESPOND    │ test-runner    │",
    r"  │              │ incident-   │ integration-   │",
    r"  │  DOCUMENT    │  commander  │  tester        │",
    r"  │ docs-writer  │             │ env-checker    │",
    r"  └──────────────┴─────────────┴───────────────┘",
]

PERMISSIONS_ART = [
    r"  ┌─────────────────────────────────────────────────┐",
    r"  │           AGENT PERMISSION TIERS                 │",
    r"  ├─────────────────────────────────────────────────┤",
    r"  │  READ ONLY  (10)  Can look. Can't touch.        │",
    r"  │  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  │",
    r"  │  READ+BASH  (3)   Can run tests. Can't edit.   │",
    r"  │  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  │",
    r"  │  READ+WRITE (1)   Can edit docs. Can't run.    │",
    r"  │  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  │",
    r"  │  FULL       (4)   Full power. Isolated.        │",
    r"  │  ████████████████████████████████████████████   │",
    r"  ├─────────────────────────────────────────────────┤",
    r"  │  14 of 18 agents have RESTRICTED permissions.   │",
    r"  └─────────────────────────────────────────────────┘",
]

DISTINCTION_ART = [
    r"  ┌──────────┬──────────────┬──────────────┬──────────────┐",
    r"  │          │   AGENTS     │   SKILLS     │   HOOKS      │",
    r"  ├──────────┼──────────────┼──────────────┼──────────────┤",
    r"  │ What     │ AI actors    │ Knowledge    │ Scripts      │",
    r"  │ Has AI?  │ Yes          │ No (teaches) │ No (enforces)│",
    r"  │ Decides? │ Yes-judgment │ No-informs   │ No-reacts    │",
    r"  │ Runs     │ On dispatch  │ When loaded  │ On events    │",
    r"  │ Can fail │ Yes (retry)  │ N/A          │ Yes (blocks) │",
    r"  │ Count    │ 18           │ 7            │ 4            │",
    r"  │ Lives in │ agents/      │ skills/      │ hooks/       │",
    r"  └──────────┴──────────────┴──────────────┴──────────────┘",
]

HOOK_DEMO_ART = [
    r"  You type:  git rebase main                    ",
    r"                                                ",
    r"  ┌────────────────────────────────────────────┐",
    r"  │  hooks/git_safety.py fires                 │",
    r"  │                                            │",
    r"  │  >>> BLOCKED <<<                            │",
    r"  │                                            │",
    r"  │  'git rebase rewrites published history.   │",
    r"  │   Use git pull origin <branch> instead.'   │",
    r"  │                                            │",
    r"  │  The command NEVER executes.               │",
    r"  └────────────────────────────────────────────┘",
]

# ── Pages ──────────────────────────────────────────────

SECTIONS = [
    "Welcome",
    "The Problem",
    "Components",
    "Agents",
    "Hooks & Rules",
    "Getting Started",
    "What's Next",
]

PAGES = [
    # ── Section 0: Welcome ─────────────────────────────
    {
        "title": "Welcome to paw",
        "section": "Welcome",
        "art": PAW_LOGO,
        "art_color": 1,  # cyan
        "body": [
            "",
            "an AI SDLC starter kit",
            "",
            "Your AI agent writes code fast.",
            "paw makes sure it writes code right.",
            "",
            "This tutorial walks you through how paw works",
            "and how to start using it today.",
            "",
            "It takes about 5 minutes.",
        ],
        "typewriter_title": True,
    },
    {
        "title": "What You'll Learn",
        "section": "Welcome",
        "body": [
            "",
            "  1.  Why your AI agent needs standards",
            "",
            "  2.  The 5 components of paw:",
            "      agents, skills, hooks, rules, contexts",
            "",
            "  3.  How hooks block bad operations",
            "",
            "  4.  How to run review agents",
            "",
            "  5.  How to start using paw today",
            "      (Claude Code, Cursor, or Codex CLI)",
        ],
    },
    # ── Section 1: The Problem ─────────────────────────
    {
        "title": "The Problem",
        "section": "The Problem",
        "body": [
            "",
            '  You:    "Add a login endpoint"',
            "",
            "  AI:     + Wrote the endpoint",
            "          + Handles POST /login",
            "          + Returns a JWT",
            "",
            "          - No rate limiting",
            "          - No brute-force protection",
            "          - Logs the password in plaintext",
            "          - JWT secret is hardcoded",
            "          - No test",
            "",
            "  The AI did what you asked.",
            "  The problem is what you DIDN'T ask.",
        ],
        "highlight": {"+": 2, "-": 3},  # green for +, yellow for -
    },
    {
        "title": "Two Choices",
        "section": "The Problem",
        "body": [
            "",
            "  OPTION A:",
            "  You review everything the AI writes.",
            "  You are now a full-time AI babysitter.",
            "  That doesn't scale.",
            "",
            "",
            "  OPTION B:",
            "  You teach the AI your standards,",
            "  and build a system that enforces them",
            "  BEFORE the code reaches you.",
            "",
            "",
            "  paw is Option B.",
        ],
    },
    # ── Section 2: Components ──────────────────────────
    {
        "title": "How It All Fits Together",
        "section": "Components",
        "art": FLOW_ART,
        "art_color": 1,  # cyan
        "body": [
            "",
            "  5 layers, each works independently.",
            "  The pipeline composes them.",
            "  It doesn't gate them.",
        ],
    },
    {
        "title": "The Five Layers",
        "section": "Components",
        "body": [
            "",
            "  AGENTS     18 specialized roles, scoped permissions",
            "             Most can only READ your code.",
            "",
            "  SKILLS     7 domain knowledge bundles",
            "             Architecture, security, frontend, PHP...",
            "",
            "  RULES      6 doctrine pages -- source of truth",
            "             If rule contradicts agent, fix the agent.",
            "",
            "  HOOKS      4 enforcement triggers",
            "             Fire on Claude Code events. Hard stops.",
            "",
            "  CONTEXTS   4 mindset modes",
            "             dev, review, security, research",
        ],
    },
    {
        "title": "The Key Distinction",
        "section": "Components",
        "art": DISTINCTION_ART,
        "art_color": 3,  # yellow (default for borders)
        # Per-row colors: borders=yellow(3), header=cyan(1), data rows alternate green(2)/magenta(4)
        "art_row_colors": [3, 1, 3, 2, 4, 2, 4, 2, 4, 2, 3],
        "body": [
            "",
            "  Agents without skills are smart but",
            "  uninformed.",
            "",
            "  Skills without agents are knowledge",
            "  with no one to use it.",
            "",
            "  Hooks without either still enforce",
            "  the rules -- that's the point.",
        ],
    },
    {
        "title": "What Is An Agent, Really?",
        "section": "Components",
        "body": [
            "",
            "  An agent is an LLM given a job.",
            "",
            "  Whether it's on your laptop, in a",
            "  company product, or in a platform",
            "  like Artemis -- the concept is the same:",
            "",
            "  MODEL     An LLM (Claude, GPT, etc.)",
            "  CONTEXT   What it knows about the task",
            "  PERSONA   How it behaves (reviewer, builder)",
            "  SCOPE     What it's allowed to touch",
            "  RULES     What standards it follows",
            "  TOOLS     What actions it can take",
            "",
            "  paw's agents are markdown files that",
            "  define all six of these. That's it.",
            "  No magic. No framework. Just a scoped",
            "  LLM with a clear job description.",
        ],
    },
    # ── Section 3: Agents ──────────────────────────────
    {
        "title": "18 Agents, 5 Phases",
        "section": "Agents",
        "art": AGENTS_ART,
        "art_color": 1,
        "body": [
            "",
            "  Each agent owns a phase or dimension.",
            "  Each has minimum permissions for its job.",
        ],
    },
    {
        "title": "Trust Through Structural Limitation",
        "section": "Agents",
        "art": PERMISSIONS_ART,
        "art_color": 4,  # magenta
        "body": [
            "",
            "  The security-reviewer CANNOT modify your code.",
            "  The test-runner CANNOT edit source files.",
            "  The builder has full power -- but it's the only one.",
        ],
    },
    {
        "title": "Using Agents",
        "section": "Agents",
        "body": [
            "",
            "  Ask by name in any AI coding tool:",
            "",
            "  Claude Code / Codex CLI:",
            "    > Use the architect agent to design",
            "      a solution for password reset.",
            "",
            "  Cursor:",
            "    Add agents as @docs or custom rules.",
            "    Reference them in your prompts.",
            "",
            "  All tools:",
            "    > Use code-reviewer, bug-auditor, and",
            "      security-reviewer on the current diff.",
            "",
            "  Three perspectives. Different catches.",
        ],
    },
    # ── Section 4: Hooks & Rules ───────────────────────
    {
        "title": "Hooks: Mechanical Enforcement",
        "section": "Hooks & Rules",
        "art": HOOK_DEMO_ART,
        "art_color": 3,  # yellow
        "body": [
            "",
            "  Hooks fire on Claude Code lifecycle events.",
            "  They don't suggest. They BLOCK.",
            "  The dangerous command never executes.",
        ],
    },
    {
        "title": "The Four Hooks",
        "section": "Hooks & Rules",
        "body": [
            "",
            "  git_safety.py        (PreToolUse)",
            "    Blocks rebase, force-push, reset --hard",
            "",
            "  branch_guard.py      (PreToolUse)",
            "    Blocks commits on main/master/develop",
            "",
            "  auto_test_detect.sh  (PostToolUse)",
            "    Warns when source file has no test",
            "",
            "  _lib.py              (Shared helpers)",
            "    read_payload, emit, find_project_root",
            "",
            "  Each hook is pipe-testable standalone.",
            "  Wire them into ~/.claude/settings.json.",
        ],
    },
    {
        "title": "Rules: Standards as Doctrine",
        "section": "Hooks & Rules",
        "body": [
            "",
            "  6 rules. Each is a markdown file.",
            "  Anyone can read them. Anyone can propose changes.",
            "  But they're enforced, not suggested.",
            "",
            "  git-doctrine       Always merge, never rebase",
            "  test-first         Tests before code, always",
            "  error-handling     No silent failures, ever",
            "  no-secrets-in-code Secrets in env vars only",
            "  branch-hygiene     Feature branch per task",
            "  security-basics    Validate input, encode output",
            "",
            "  Rule --> Agent enforces --> Hook blocks",
        ],
    },
    # ── Section 5: Getting Started ─────────────────────
    {
        "title": "Install in 2 Minutes",
        "section": "Getting Started",
        "body": [
            "",
            "  Step 1: Clone paw",
            "",
            "    git clone https://github.com/zofrus/paw ~/.paw",
            "",
            "  Step 2: Add hooks to ~/.claude/settings.json:",
            "",
            '    "hooks": {',
            '      "PreToolUse": [{',
            '        "matcher": "Bash",',
            '        "hooks": [',
            '          {"type":"command",',
            '           "command":"python3 ~/.paw/hooks/git_safety.py"},',
            '          {"type":"command",',
            '           "command":"python3 ~/.paw/hooks/branch_guard.py"}',
            "        ]",
            "      }]",
            "    }",
        ],
    },
    {
        "title": "Try It Right Now",
        "section": "Getting Started",
        "body": [
            "",
            "  After installing, open Claude Code and try:",
            "",
            "    > run git rebase main",
            "",
            "  You'll see:",
            "",
            "    BLOCKED",
            '    "git rebase rewrites published history.',
            '     Use git pull origin <branch> instead."',
            "",
            "  Then try running a review agent:",
            "",
            "    > Use the code-reviewer agent on the",
            "      current diff.",
            "",
            "  See what it finds that you wouldn't have.",
        ],
    },
    # ── Section 6: What's Next ─────────────────────────
    {
        "title": "What's Next",
        "section": "What's Next",
        "art": ROCKET_ART,
        "art_color": 2,  # green
        "body": [
            "",
            "  TODAY:  Install hooks. Try an agent.",
            "",
            "  THIS WEEK:  Run 3 reviewers on a PR.",
            "    code-reviewer + bug-auditor + security",
            "",
            "  NEXT WEEK:  Full workflow.",
            "    architect -> planner -> devils-advocate",
            "    -> builder -> code-reviewer",
            "",
            "  WHEN READY:  Graduate to forge.",
            "    46 agents, 15 parallel gates.",
            "",
            "  Works with: Claude Code, Cursor, Codex CLI",
            "",
            "  Press -> for a detailed info screen.",
        ],
        "typewriter_title": True,
    },
]
