"""
paw tutorial content — multi-track tutorial library.
Pages are dicts with: title, section, body (list of lines), art (optional).
"""

# ── ASCII Art ──────────────────────────────────────────────

PAW_LOGO = [
    r"        _______________        ",
    r"       /               \       ",
    r"      |  ┌───┐ ┌───┐  |       ",
    r"      |  │ ● │ │ ● │  |       ",
    r"      |  └───┘ └───┘  |       ",
    r"      |      ___      |       ",
    r"      |     /   \     |       ",
    r"      |    | === |    |       ",
    r"       \   \_____/   /        ",
    r"        \___________/         ",
    r"         /    |    \          ",
    r"        *     *     *         ",
]

SHIELD_ART = [
    r"       ╔═══════════╗    ",
    r"       ║  ┌─────┐  ║    ",
    r"       ║  │ ██  │  ║    ",
    r"       ║  │ ███ │  ║    ",
    r"       ║  │ ██  │  ║    ",
    r"       ║  └─────┘  ║    ",
    r"       ╚═════╦═════╝    ",
    r"             ║          ",
    r"         HOOKS          ",
    r"       ENFORCE          ",
]

FLOW_ART = [
    r"  ┌──────────┐     ┌──────────┐     ┌──────────┐  ",
    r"  │  AGENTS  │────▶│  SKILLS  │     │ CONTEXTS │  ",
    r"  │ 18 roles │     │  domain  │     │  mindset │  ",
    r"  └────┬─────┘     └──────────┘     └──────────┘  ",
    r"       │                                  │        ",
    r"       │ reference                   loaded by     ",
    r"       ▼                                  │        ",
    r"  ┌──────────┐                            │        ",
    r"  │  RULES   │◄───────────────────────────┘        ",
    r"  │ 6 pages  │                                     ",
    r"  └────┬─────┘                                     ",
    r"       │ enforced by                               ",
    r"       ▼                                           ",
    r"  ┌──────────┐                                     ",
    r"  │  HOOKS   │  ◄── fire on Claude Code events     ",
    r"  └──────────┘                                     ",
]

ROCKET_ART = [
    r"           /\          ",
    r"          /  \         ",
    r"         / || \        ",
    r"        /  ||  \       ",
    r"       /   ||   \      ",
    r"      / ┌──────┐ \    ",
    r"     /  │ paw  │  \   ",
    r"    /   │  =>  │   \  ",
    r"   /    │forge │    \ ",
    r"  ╱     └──────┘     ╲",
    r" ╱___________________╲",
    r"     ╱╱╱    ╲╲╲       ",
    r"    ╱╱╱      ╲╲╲      ",
]

AGENTS_ART = [
    r"  ┌────────────────────────────────────────────┐",
    r"  │          18 SPECIALIZED AGENTS              │",
    r"  ├──────────────┬─────────────┬───────────────┤",
    r"  │   PLAN       │  BUILD      │  REVIEW       │",
    r"  ├──────────────┼─────────────┼───────────────┤",
    r"  │ architect    │ builder     │ code-reviewer  │",
    r"  │ planner      │ merge-      │ bug-auditor    │",
    r"  │ devils-      │  resolver   │ security       │",
    r"  │  advocate    │ migration-  │ perf-checker   │",
    r"  │ rollback-    │  architect  │ fe-reviewer    │",
    r"  │  planner     │             │ php-reviewer   │",
    r"  │              │  RESPOND    │ test-runner    │",
    r"  │              │ incident-   │ integration-   │",
    r"  │  DOCUMENT    │  commander  │  tester        │",
    r"  │ docs-writer  │             │ env-checker    │",
    r"  └──────────────┴─────────────┴───────────────┘",
]

PERMISSIONS_ART = [
    r"  ┌─────────────────────────────────────────────────┐",
    r"  │           AGENT PERMISSION TIERS                 │",
    r"  ├─────────────────────────────────────────────────┤",
    r"  │  READ ONLY  (10)  Can look. Can't touch.        │",
    r"  │  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  │",
    r"  │  READ+BASH  (3)   Can run tests. Can't edit.   │",
    r"  │  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  │",
    r"  │  READ+WRITE (1)   Can edit docs. Can't run.    │",
    r"  │  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  │",
    r"  │  FULL       (4)   Full power. Isolated.        │",
    r"  │  ████████████████████████████████████████████   │",
    r"  ├─────────────────────────────────────────────────┤",
    r"  │  14 of 18 agents have RESTRICTED permissions.   │",
    r"  └─────────────────────────────────────────────────┘",
]

HOOK_DEMO_ART = [
    r"  You type:  git rebase main                    ",
    r"                                                ",
    r"  ┌────────────────────────────────────────────┐",
    r"  │  hooks/git_safety.py fires                 │",
    r"  │                                            │",
    r"  │  >>> BLOCKED <<<                            │",
    r"  │                                            │",
    r"  │  'git rebase rewrites published history.   │",
    r"  │   Use git pull origin <branch> instead.'   │",
    r"  │                                            │",
    r"  │  The command NEVER executes.               │",
    r"  └────────────────────────────────────────────┘",
]

DISTINCTION_ART = [
    r"  ┌──────────┬──────────────┬──────────────┬──────────────┐",
    r"  │          │   AGENTS     │   SKILLS     │   HOOKS      │",
    r"  ├──────────┼──────────────┼──────────────┼──────────────┤",
    r"  │ What     │ AI actors    │ Knowledge    │ Scripts      │",
    r"  │ Has AI?  │ Yes          │ No (teaches) │ No (enforces)│",
    r"  │ Decides? │ Yes-judgment │ No-informs   │ No-reacts    │",
    r"  │ Runs     │ On dispatch  │ When loaded  │ On events    │",
    r"  │ Can fail │ Yes (retry)  │ N/A          │ Yes (blocks) │",
    r"  │ Count    │ 18           │ 7            │ 4            │",
    r"  │ Lives in │ agents/      │ skills/      │ hooks/       │",
    r"  └──────────┴──────────────┴──────────────┴──────────────┘",
]

FOUR_BLOCKS_ART = [
    r"  ┌──────────────────────────────────────────────┐",
    r"  │        FOUR BUILDING BLOCKS                   │",
    r"  ├──────────────────────────────────────────────┤",
    r"  │                                              │",
    r"  │  AGENT  =  WHO does the work                 │",
    r"  │  SKILL  =  WHAT it knows how to do           │",
    r"  │  HOOK   =  WHEN it runs automatically        │",
    r"  │  RULE   =  WHY it matters                    │",
    r"  │                                              │",
    r"  │  That's the whole thing.                     │",
    r"  └──────────────────────────────────────────────┘",
]

PORTABLE_ART = [
    r"  ┌──────────────────────────────────────────────┐",
    r"  │  YOUR AGENTS + RULES = PORTABLE              │",
    r"  ├──────────────────────────────────────────────┤",
    r"  │                                              │",
    r"  │  Claude Code    ✓  reads your .md files      │",
    r"  │  Cursor         ✓  reads your .md files      │",
    r"  │  Codex CLI      ✓  reads your .md files      │",
    r"  │  Whatever's     ✓  they're just markdown     │",
    r"  │   next                                       │",
    r"  │                                              │",
    r"  │  Company platforms don't travel with you.    │",
    r"  │  Agents and rules you write are YOURS.       │",
    r"  └──────────────────────────────────────────────┘",
]

CLI_ART = [
    r"  ┌────────────────────────────────────────────┐",
    r"  │  $ paw <command>                           │",
    r"  ├────────────────────────────────────────────┤",
    r"  │  setup       install hooks + check reqs    │",
    r"  │  tutorial    this TUI walkthrough           │",
    r"  │  doctor      diagnose your install          │",
    r"  │  init        scaffold .paw.json config     │",
    r"  │  check       run quality gate              │",
    r"  │  gate <name> run a single agent            │",
    r"  │  agents      list all 18 agents            │",
    r"  │  version     show version                  │",
    r"  └────────────────────────────────────────────┘",
]

BUGGY_ART = [
    r"  ┌────────────────────────────────────────────┐",
    r"  │  examples/buggy-app/app.py                 │",
    r"  ├────────────────────────────────────────────┤",
    r"  │  6 security holes     (can you find them?) │",
    r"  │  4 latent bugs        (race, off-by-one)   │",
    r"  │  1 N+1 query          (perf)               │",
    r"  │  0 tests              (oops)               │",
    r"  │  0 input validation   (yikes)              │",
    r"  └────────────────────────────────────────────┘",
]

# ── Track definitions ─────────────────────────────────

TRACKS = [
    {
        "id": "learn",
        "title": "Learn paw",
        "desc": "What paw is, the 5 components, concepts",
        "time": "~5 min",
        "icon": "📖",
    },
    {
        "id": "start",
        "title": "Getting started",
        "desc": "Install hooks, run agents, hands-on",
        "time": "~5 min",
        "icon": "🚀",
    },
    {
        "id": "cli",
        "title": "The paw CLI",
        "desc": "Commands, presets, init, doctor",
        "time": "~3 min",
        "icon": "⌨",
    },
    {
        "id": "advanced",
        "title": "Advanced tactics",
        "desc": "Workflows, team config, customization",
        "time": "~4 min",
        "icon": "⚙",
    },
    {
        "id": "practice",
        "title": "Practice with examples",
        "desc": "Run agents against a buggy app",
        "time": "~5 min",
        "icon": "🐛",
    },
    {
        "id": "try",
        "title": "Try this week",
        "desc": "Build your first agent, rule, skill, hook",
        "time": "~3 min",
        "icon": "🎯",
    },
    {
        "id": "contribute",
        "title": "Contributing to paw",
        "desc": "Fork, test, submit a PR",
        "time": "~2 min",
        "icon": "🤝",
    },
]

# ── Track: Learn paw ──────────────────────────────────

MECHANICAL_ART = [
    r"  BEFORE (tribal knowledge):              ",
    r"  ┌──────────────────────────────────────┐ ",
    r"  │  'Hey, don't forget to write tests'  │ ",
    r"  │  'We don't rebase here'              │ ",
    r"  │  'Make sure you validate input'      │ ",
    r"  └──────────────────────────────────────┘ ",
    r"                                           ",
    r"  AFTER (mechanical enforcement):          ",
    r"  ┌──────────────────────────────────────┐ ",
    r"  │  rules/test-first.md                 │ ",
    r"  │    → test-runner gate BLOCKS          │ ",
    r"  │  rules/git-doctrine.md               │ ",
    r"  │    → hooks/git_safety.py BLOCKS       │ ",
    r"  │  rules/security-basics.md            │ ",
    r"  │    → security-reviewer REPORTS        │ ",
    r"  └──────────────────────────────────────┘ ",
]

SMART_TOOLS_ART = [
    r"  ┌────────────────────────────────────────────┐",
    r"  │  $ paw suggest                             │",
    r"  ├────────────────────────────────────────────┤",
    r"  │  Detected: Node.js + React                 │",
    r"  │  Recommended agents:                       │",
    r"  │    ✓ fe-reviewer     (React/JSX)            │",
    r"  │    ✓ security        (npm audit)            │",
    r"  │    ✗ php-reviewer    (not needed)           │",
    r"  └────────────────────────────────────────────┘",
]

CONTRIBUTE_ART = [
    r"  ┌────────────────────────────────────────────┐",
    r"  │         CONTRIBUTING TO PAW                 │",
    r"  ├────────────────────────────────────────────┤",
    r"  │                                            │",
    r"  │  Fork  →  Branch  →  Test  →  PR           │",
    r"  │                                            │",
    r"  │  python3 -m pytest tests/ -v               │",
    r"  │  ruff check .                              │",
    r"  │  ruff format --check .                     │",
    r"  │                                            │",
    r"  │  All PRs require maintainer approval.      │",
    r"  └────────────────────────────────────────────┘",
]

LEARN_SECTIONS = [
    "Welcome",
    "The Problem",
    "Components",
    "Agents",
    "Hooks & Rules",
]

LEARN_PAGES = [
    {
        "title": "Welcome to paw",
        "section": "Welcome",
        "art": PAW_LOGO,
        "art_color": 1,
        "body": [
            "",
            "Personal Agent Workflows",
            "an AI SDLC starter kit",
            "",
            "Your AI agent writes code fast.",
            "paw makes sure it writes code right.",
            "",
            "This track covers what paw is",
            "and how it works.",
        ],
        "typewriter_title": True,
    },
    {
        "title": "The Problem",
        "section": "The Problem",
        "body": [
            "",
            '  You:    "Add a login endpoint"',
            "",
            "  AI:     + Wrote the endpoint",
            "          + Handles POST /login",
            "          + Returns a JWT",
            "",
            "          - No rate limiting",
            "          - No brute-force protection",
            "          - Logs the password in plaintext",
            "          - JWT secret is hardcoded",
            "          - No test",
            "",
            "  The AI did what you asked.",
            "  The problem is what you DIDN'T ask.",
        ],
        "highlight": {"+": 2, "-": 3},
    },
    {
        "title": "Two Choices",
        "section": "The Problem",
        "body": [
            "",
            "  OPTION A:",
            "  You review everything the AI writes.",
            "  You are now a full-time AI babysitter.",
            "  That doesn't scale.",
            "",
            "",
            "  OPTION B:",
            "  You teach the AI your standards,",
            "  and build a system that enforces them",
            "  BEFORE the code reaches you.",
            "",
            "",
            "  paw is Option B.",
        ],
    },
    {
        "title": "How It All Fits Together",
        "section": "Components",
        "art": FLOW_ART,
        "art_color": 1,
        "body": [
            "",
            "  5 layers, each works independently.",
            "  The pipeline composes them.",
            "  It doesn't gate them.",
        ],
    },
    {
        "title": "Four Building Blocks",
        "section": "Components",
        "art": FOUR_BLOCKS_ART,
        "art_color": 2,
        "body": [
            "",
            "  AGENT  Give it a name, a model, a persona,",
            "         specific expertise. 'You are a",
            "         thorough code reviewer who catches",
            "         edge cases.'",
            "",
            "  SKILL  Instructions for a specific task.",
            "         'When reviewing, check for security,",
            "         test coverage, and naming.'",
            "",
            "  HOOK   A trigger that fires on an event.",
            "         'Before every commit, run the linter.",
            "         If it fails, block it.' Enforceable.",
            "",
            "  RULE   The standards being suggested.",
            "         'All functions must have error",
            "         handling.' Rules can be broken --",
            "         hooks can't.",
        ],
    },
    {
        "title": "Portable by Design",
        "section": "Components",
        "art": PORTABLE_ART,
        "art_color": 1,
        "body": [
            "",
            "  If you build agents and rules around YOUR",
            "  workflow, they work in any AI tool.",
            "",
            "  Claude, Cursor, Copilot, whatever's next.",
            "",
            "  If you get good at a company platform",
            "  and then leave -- you can't take it.",
            "",
            "  If you get good at writing agents and",
            "  rules -- that's yours forever.",
            "",
            "  paw agents are just markdown files.",
            "  No vendor lock-in. No magic.",
        ],
    },
    {
        "title": "The Key Distinction",
        "section": "Components",
        "art": DISTINCTION_ART,
        "art_color": 3,
        "art_row_colors": [3, 1, 3, 2, 4, 2, 4, 2, 4, 2, 3],
        "body": [
            "",
            "  Agents without skills are smart but",
            "  uninformed.",
            "",
            "  Skills without agents are knowledge",
            "  with no one to use it.",
            "",
            "  Hooks without either still enforce",
            "  the rules -- that's the point.",
        ],
    },
    {
        "title": "18 Agents, 5 Phases",
        "section": "Agents",
        "art": AGENTS_ART,
        "art_color": 1,
        "body": [
            "",
            "  Each agent owns a phase or dimension.",
            "  Each has minimum permissions for its job.",
        ],
    },
    {
        "title": "Trust Through Structural Limitation",
        "section": "Agents",
        "art": PERMISSIONS_ART,
        "art_color": 4,
        "body": [
            "",
            "  The security-reviewer CANNOT modify code.",
            "  The test-runner CANNOT edit source files.",
            "  Only 4 of 18 get full access.",
        ],
    },
    {
        "title": "Hooks: Mechanical Enforcement",
        "section": "Hooks & Rules",
        "art": HOOK_DEMO_ART,
        "art_color": 3,
        "body": [
            "",
            "  Hooks fire on Claude Code lifecycle events.",
            "  They don't suggest. They BLOCK.",
            "  The dangerous command never executes.",
        ],
    },
    {
        "title": "Rules: Standards as Doctrine",
        "section": "Hooks & Rules",
        "body": [
            "",
            "  6 rules. Each is a markdown file.",
            "  Anyone can read them. Anyone can propose",
            "  changes. But they're enforced, not suggested.",
            "",
            "  git-doctrine       Always merge, never rebase",
            "  test-first         Tests before code, always",
            "  error-handling     No silent failures, ever",
            "  no-secrets-in-code Secrets in env vars only",
            "  branch-hygiene     Feature branch per task",
            "  security-basics    Validate input, encode output",
            "",
            "  Rule --> Agent enforces --> Hook blocks",
        ],
    },
    {
        "title": "Mechanical, Not Cultural",
        "section": "Hooks & Rules",
        "art": MECHANICAL_ART,
        "art_color": 3,
        "body": [
            "",
            "  Tribal knowledge gets forgotten.",
            "  Style guides get skipped.",
            "  Code review catches it... sometimes.",
            "",
            "  paw makes enforcement mechanical:",
            "",
            "  Rule  -->  Agent enforces it",
            "        -->  Hook prevents violations",
            "",
            "  The AI doesn't need to remember your",
            "  standards. The system enforces them.",
        ],
    },
]

# ── Track: Getting started ────────────────────────────

START_SECTIONS = [
    "Setup",
    "Try Hooks",
    "Try Agents",
    "What's Next",
]

START_PAGES = [
    {
        "title": "Install in 2 Minutes",
        "section": "Setup",
        "body": [
            "",
            "  Step 1: Clone paw (anywhere you want)",
            "",
            "    git clone https://github.com/zofrus/paw ~/paw",
            "    cd ~/paw",
            "",
            "  Step 2: Run setup",
            "",
            "    ./paw setup",
            "",
            "  That's it. Setup:",
            "    - Checks Python, git, terminal",
            "    - Installs hooks with correct paths",
            "    - Backs up your settings first",
            "    - Verifies everything works",
            "",
            "  Clone to ~/paw, ~/tools/paw, anywhere.",
            "  Setup detects the path automatically.",
        ],
    },
    {
        "title": "Test the Hooks",
        "section": "Try Hooks",
        "art": HOOK_DEMO_ART,
        "art_color": 3,
        "body": [
            "",
            "  Open Claude Code and type:",
            "",
            "    > run git rebase main",
            "",
            "  It will be BLOCKED with an explanation.",
            "  The command never executes.",
        ],
    },
    {
        "title": "More Hook Tests",
        "section": "Try Hooks",
        "body": [
            "",
            "  Try these too:",
            "",
            "  > run git push --force origin main",
            "    BLOCKED -- overwrites remote history",
            "",
            "  > run git reset --hard HEAD~1",
            "    BLOCKED -- discards uncommitted work",
            "",
            "  > run git commit -m 'test'   (on main)",
            "    BLOCKED -- create a feature branch",
            "",
            "  > run git push --force-with-lease origin feat",
            "    ALLOWED -- safe alternative to --force",
        ],
    },
    {
        "title": "Run a Review Agent",
        "section": "Try Agents",
        "body": [
            "",
            "  Make sure you have a diff (any changes).",
            "  Then type in Claude Code:",
            "",
            "    > Use the code-reviewer agent on the",
            "      current diff.",
            "",
            "  Look at the findings. Ask yourself:",
            "    - Did it catch anything you'd catch?",
            "    - Did it catch anything you WOULDN'T?",
            "    - Are the severity levels honest?",
        ],
    },
    {
        "title": "Stack Multiple Reviewers",
        "section": "Try Agents",
        "body": [
            "",
            "  Now run all three:",
            "",
            "    > Use the code-reviewer, bug-auditor,",
            "      and security-reviewer agents on the",
            "      current diff.",
            "",
            "  Or use the paw CLI:",
            "",
            "    $ paw check",
            "",
            "  Three independent perspectives.",
            "  Each catches different things.",
            "  No single reviewer covers all dimensions.",
        ],
    },
    {
        "title": "What's Next",
        "section": "What's Next",
        "art": ROCKET_ART,
        "art_color": 2,
        "body": [
            "",
            "  TODAY:  Keep the hooks on. Run an agent.",
            "",
            "  THIS WEEK:  paw check on your next PR.",
            "",
            "  NEXT WEEK:  Try the full workflow.",
            "    architect -> planner -> devils-advocate",
            "    -> builder -> code-reviewer",
            "",
            "  Run the CLI track to learn paw commands.",
            "  Run the Practice track to try the buggy app.",
        ],
        "typewriter_title": True,
    },
]

# ── Track: The paw CLI ────────────────────────────────

CLI_SECTIONS = [
    "Overview",
    "Quality Gates",
    "Smart Tools",
    "Config & Health",
]

CLI_PAGES = [
    {
        "title": "The paw CLI",
        "section": "Overview",
        "art": CLI_ART,
        "art_color": 1,
        "body": [
            "",
            "  One command for everything.",
            "  Tab-completable. No memorizing prompts.",
        ],
    },
    {
        "title": "Quality Gate Presets",
        "section": "Quality Gates",
        "body": [
            "",
            "  Three presets for different situations:",
            "",
            "  paw check --quick",
            "    code-reviewer only. Fast feedback.",
            "",
            "  paw check",
            "    code + bugs + security. The default.",
            "    Use before requesting code review.",
            "",
            "  paw check --thorough",
            "    All 8 reviewers. Before merging big",
            "    features or security-sensitive code.",
        ],
    },
    {
        "title": "Single Gates & Agent List",
        "section": "Quality Gates",
        "body": [
            "",
            "  Run a single agent:",
            "",
            "    paw gate security",
            "    paw gate bugs",
            "    paw gate perf",
            "    paw gate frontend",
            "    paw gate php",
            "    paw gate tests",
            "    paw gate docs",
            "    paw gate env",
            "",
            "  List all agents:",
            "",
            "    paw agents",
        ],
    },
    {
        "title": "Smart Suggestions",
        "section": "Smart Tools",
        "art": SMART_TOOLS_ART,
        "art_color": 2,
        "body": [
            "",
            "  paw suggest",
            "    Reads your project files. Detects your",
            "    stack (Node, PHP, Python, Go, Rust).",
            "    Recommends which agents to enable.",
            "",
            "  paw next",
            "    Tracks your progress through paw.",
            "    Suggests the next thing to try based",
            "    on what you've already done.",
            "",
            "  paw cheatsheet",
            "    One-screen quick reference card.",
            "    All commands, agents, prompts, workflows.",
            "    Also available as printable PDF.",
        ],
    },
    {
        "title": "paw init — Team Config",
        "section": "Config & Health",
        "body": [
            "",
            "  Scaffold a config for your project:",
            "",
            "    paw init",
            "",
            "  Creates .paw.json with:",
            "    - agents.enabled -- which agents run",
            "    - agents.disabled -- which to skip",
            "    - quality_gate.default_preset",
            "    - history settings",
            "",
            "  Check .paw.json into version control.",
            "  Your whole team shares the config.",
        ],
    },
    {
        "title": "paw doctor — Diagnose Issues",
        "section": "Config & Health",
        "body": [
            "",
            "  Something broken? Run:",
            "",
            "    paw doctor",
            "",
            "  Checks:",
            "    - Python version and curses module",
            "    - Hook files exist and are executable",
            "    - Hooks installed in settings.json",
            "    - All 18 agent files present",
            "    - Hook self-test (actually blocks)",
            "    - Test suite passes",
            "",
            "  Tells you exactly what's wrong",
            "  and how to fix it.",
        ],
    },
]

# ── Track: Advanced tactics ───────────────────────────

ADVANCED_SECTIONS = [
    "Workflows",
    "Customizing",
    "Scaling Up",
]

ADVANCED_PAGES = [
    {
        "title": "The Full Workflow",
        "section": "Workflows",
        "body": [
            "",
            "  Plan -> Critique -> Build -> Review",
            "",
            "  1. Use the architect agent to design",
            "     a solution for [your task].",
            "",
            "  2. Use the planner agent to turn the",
            "     architecture into a plan.",
            "",
            "  3. Use the devils-advocate agent to",
            "     critique the plan.",
            "",
            "  4. Use the builder agent to implement.",
            "",
            "  5. Use the code-reviewer agent on",
            "     the changes.",
            "",
            "  The devil's advocate attacks the plan",
            "  BEFORE any code is written.",
        ],
    },
    {
        "title": "Incident Response",
        "section": "Workflows",
        "body": [
            "",
            "  Production fire? Use the workflow:",
            "",
            "  1. Use the incident-commander agent.",
            "     Stop bleeding > root cause > prevent.",
            "",
            "  2. Use the rollback-planner agent.",
            "     Every fix needs a way back.",
            "",
            "  3. Use the environment-checker agent.",
            "     Verify the fix actually worked.",
            "",
            "  The incident-commander loads the",
            "  security context -- adversarial mindset,",
            "  assume worst case.",
        ],
    },
    {
        "title": "Workshop: Write Your Own Rule",
        "section": "Customizing",
        "body": [
            "",
            "  Think of one standard your team follows",
            "  that ISN'T written down anywhere.",
            "",
            "  Now write it as a rule:",
            "",
            "  Create rules/your-rule.md:",
            "",
            "  # [Rule Name]",
            "  **Statement:** One sentence.",
            "  **Why:** Why this matters.",
            "  ## Hard rules",
            "  - ...",
            "  **Enforced by:** which agent checks this?",
            "",
            "  Reference it in the agent's Rules section.",
            "  The rule is now mechanically enforced --",
            "  not tribal knowledge that gets forgotten.",
        ],
    },
    {
        "title": "Adding Your Own Agent",
        "section": "Customizing",
        "body": [
            "",
            "  Create agents/your-agent.md:",
            "",
            "  ---",
            "  name: your-agent",
            "  description: What it does.",
            "  model: sonnet",
            "  tools: Read, Grep, Glob",
            "  ---",
            "",
            "  Then add:",
            "    Role, Context, Rules, Process,",
            "    Failure modes, Done when.",
            "",
            "  Most agents are read-only.",
            "  Only grant write/bash when needed.",
        ],
    },
    {
        "title": "paw to forge",
        "section": "Scaling Up",
        "art": ROCKET_ART,
        "art_color": 2,
        "body": [
            "",
            "  paw                    forge",
            "  18 agents              46 agents",
            "  Manual invocation      16-phase pipeline",
            "  You sequence work      Orchestrator does",
            "  You run reviews        15 gates parallel",
            "  4 hooks                8 + self-healing",
            "  6 rules                21 doctrine pages",
            "",
            "  Start with paw.",
            "  Graduate to forge when you're ready.",
        ],
    },
]

# ── Track: Practice with examples ─────────────────────

PRACTICE_SECTIONS = [
    "The Buggy App",
    "Run Agents",
    "Results",
]

PRACTICE_PAGES = [
    {
        "title": "Meet the Buggy App",
        "section": "The Buggy App",
        "art": BUGGY_ART,
        "art_color": 3,
        "body": [
            "",
            "  examples/buggy-app/app.py is a",
            "  deliberately broken Python app.",
            "",
            "  Your mission: run paw's review agents",
            "  and see how many issues they find.",
            "",
            "  Don't read the README spoilers yet.",
        ],
    },
    {
        "title": "What to Look For",
        "section": "The Buggy App",
        "body": [
            "",
            "  The app has problems in every category:",
            "",
            "  SECURITY   Hardcoded secrets, injection,",
            "             plaintext passwords in logs",
            "",
            "  BUGS       Off-by-one, race condition,",
            "             bare except that swallows errors",
            "",
            "  PERF       N+1 query in a loop",
            "",
            "  QUALITY    Zero tests, no input validation,",
            "             no error handling on DB connection",
            "",
            "  How many can the agents find?",
        ],
    },
    {
        "title": "Run the Security Reviewer",
        "section": "Run Agents",
        "body": [
            "",
            "  Start with security:",
            "",
            "    > Use the security-reviewer agent on",
            "      examples/buggy-app/",
            "",
            "  Or: paw gate security",
            "  (then point it at the buggy app)",
            "",
            "  Look for: OWASP categories, severity",
            "  levels, exploit paths.",
            "",
            "  How many of the 6 security holes",
            "  does it find?",
        ],
    },
    {
        "title": "Run the Bug Auditor",
        "section": "Run Agents",
        "body": [
            "",
            "  Now bugs:",
            "",
            "    > Use the bug-auditor agent on",
            "      examples/buggy-app/",
            "",
            "  Or: paw gate bugs",
            "",
            "  Look for: reproduction scenarios,",
            "  the checklist categories (off-by-one,",
            "  race condition, bare except, etc.)",
            "",
            "  How many of the 4 bugs does it find?",
        ],
    },
    {
        "title": "Run the Perf Checker",
        "section": "Run Agents",
        "body": [
            "",
            "  Performance:",
            "",
            "    > Use the perf-checker agent on",
            "      examples/buggy-app/",
            "",
            "  Or: paw gate perf",
            "",
            "  Look for: the N+1 query pattern.",
            "  Does it explain WHY it's a problem",
            "  at scale?",
            "",
            "  Good findings include scale impact:",
            '  "fine at 100, breaks at 100K"',
        ],
    },
    {
        "title": "Check Your Results",
        "section": "Results",
        "body": [
            "",
            "  Open examples/buggy-app/README.md",
            "  and click the spoiler tag.",
            "",
            "  Compare what the agents found vs",
            "  the full list of issues.",
            "",
            "  Questions to consider:",
            "",
            "  - Did each agent stay in its lane?",
            "    (security didn't report perf issues?)",
            "  - Were severity levels accurate?",
            "  - Would you have caught all of these",
            "    in a manual review?",
            "",
            "  Now try: paw check --thorough",
        ],
    },
]

# ── Track: Try this week ─────────────────────────────

TRY_SECTIONS = [
    "Start Here",
    "Build Yours",
]

TRY_PAGES = [
    {
        "title": "Your First Agent in 60 Seconds",
        "section": "Start Here",
        "body": [
            "",
            "  You don't need to install anything.",
            "  You don't need a framework.",
            "",
            "  Open your AI tool and paste:",
            "",
            '  "You are [your name]. You are an expert',
            "   at [thing you're good at]. When asked",
            "   to [task], you always [your approach].",
            '   You never [thing you always catch]."',
            "",
            "  That's your first agent.",
            "  Iterate from there.",
        ],
    },
    {
        "title": "Find Your Rule",
        "section": "Start Here",
        "body": [
            "",
            "  Think about one thing you check EVERY",
            "  time you review someone's work.",
            "",
            "  Maybe it's:",
            "    - Error handling on every API call",
            "    - Tests for edge cases, not just happy path",
            "    - No magic numbers without a comment",
            "    - Database queries always parameterized",
            "",
            "  Write it down. One sentence.",
            "",
            "  That's a rule. Put it in rules/your-rule.md",
            "  and your AI enforces it every time.",
        ],
    },
    {
        "title": "Find Your Skill",
        "section": "Start Here",
        "body": [
            "",
            "  Think about one repetitive task you do",
            "  the same way every time.",
            "",
            "  Maybe it's:",
            "    - How you set up a new API endpoint",
            "    - How you write a migration",
            "    - How you structure a PR description",
            "    - How you investigate a production issue",
            "",
            "  Write down the steps. That's a skill.",
            "  Put it in skills/your-skill/SKILL.md",
            "  and your agents can learn it.",
        ],
    },
    {
        "title": "Find Your Hook",
        "section": "Build Yours",
        "body": [
            "",
            "  Think about one thing that should ALWAYS",
            "  happen before you ship work.",
            "",
            "    - Check for tests?",
            "    - Run the test suite?",
            "    - Verify spec intent was met?",
            "    - Follow existing architecture patterns?",
            "    - Check for secrets in code?",
            "",
            "  That's a hook. Write a script that checks",
            "  for it and blocks if it fails.",
            "",
            "  Rules can be broken. Hooks can't.",
        ],
    },
    {
        "title": "The Whole Point",
        "section": "Build Yours",
        "art": PORTABLE_ART,
        "art_color": 1,
        "body": [
            "",
            "  You can build a personal AI workforce",
            "  that does your repetitive work the way",
            "  YOU would do it.",
            "",
            "  And you can take it with you anywhere.",
            "",
            "  Start with one agent that does one thing",
            "  you already do. That's it.",
            "",
            "  paw gives you the structure.",
            "  You bring the standards.",
        ],
        "typewriter_title": True,
    },
]

# ── Track: Contributing ──────────────────────────────

CONTRIBUTE_SECTIONS = [
    "Getting Started",
    "What to Build",
    "Submit",
]

CONTRIBUTE_PAGES = [
    {
        "title": "Contributing to paw",
        "section": "Getting Started",
        "art": CONTRIBUTE_ART,
        "art_color": 1,
        "body": [
            "",
            "  paw is open source. Contributions welcome.",
            "",
            "  All PRs require maintainer approval.",
            "  Open an issue first for large changes.",
            "",
            "  Small fixes (typos, bug fixes, tests)",
            "  can go straight to a PR.",
        ],
    },
    {
        "title": "Dev Setup",
        "section": "Getting Started",
        "body": [
            "",
            "  Fork the repo on GitHub, then:",
            "",
            "    git clone https://github.com/YOU/paw ~/paw",
            "    cd ~/paw",
            "    ./paw setup",
            "",
            "  Requirements:",
            "    - Python 3.10+",
            "    - git",
            "    - Terminal with curses (macOS/Linux)",
            "",
            "  Verify:",
            "    python3 -m pytest tests/ -v",
            "    ruff check .",
            "    ruff format --check .",
        ],
    },
    {
        "title": "What You Can Build",
        "section": "What to Build",
        "body": [
            "",
            "  AGENTS   Follow agents/architect.md pattern.",
            "           Pick a context, rules, minimum tools.",
            "           Default to read-only permissions.",
            "",
            "  RULES    Follow rules/git-doctrine.md pattern.",
            "           Statement, why, hard rules, enforced by.",
            "",
            "  SKILLS   Create skills/your-skill/SKILL.md.",
            "           Domain knowledge for agents to load.",
            "",
            "  HOOKS    Changes to hooks/ require tests.",
            "           These are security-critical code.",
            "",
            "  TESTS    More coverage always welcome.",
            "           Edge cases in hooks especially.",
        ],
    },
    {
        "title": "Before You Submit",
        "section": "Submit",
        "body": [
            "",
            "  Every PR must pass these checks:",
            "",
            "    python3 -m pytest tests/ -v",
            "    ruff check .",
            "    ruff format --check .",
            "",
            "  If ruff format fails, auto-fix:",
            "    ruff format .",
            "",
            "  PR guidelines:",
            "    - One feature or fix per PR",
            "    - Clear description of what and why",
            "    - Reference related issues",
            "    - Tests before code",
            "",
            "  See CONTRIBUTING.md for the full guide.",
        ],
    },
]

# ── Default export (learn track) for backwards compat ─

SECTIONS = LEARN_SECTIONS
PAGES = LEARN_PAGES

# ── All tracks registry ───────────────────────────────

ALL_TRACKS = {
    "learn": (LEARN_SECTIONS, LEARN_PAGES),
    "start": (START_SECTIONS, START_PAGES),
    "cli": (CLI_SECTIONS, CLI_PAGES),
    "advanced": (ADVANCED_SECTIONS, ADVANCED_PAGES),
    "practice": (PRACTICE_SECTIONS, PRACTICE_PAGES),
    "try": (TRY_SECTIONS, TRY_PAGES),
    "contribute": (CONTRIBUTE_SECTIONS, CONTRIBUTE_PAGES),
}
